
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * student.java
 *
 * Created on Jun 9, 2013, 1:38:14 PM
 */
package g_primaryschoolmanagement_client;

import static g_primaryschoolmanagement_client.search.database;
import static g_primaryschoolmanagement_client.search.dbhostip;
import static g_primaryschoolmanagement_client.search.dbpassword;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author griffin
 */
public class examreports extends javax.swing.JInternalFrame {
    /** Creates new form student */
    public examreports() {
        dblogincred();
        initComponents();
        try {
    for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
            UIManager.setLookAndFeel(info.getClassName());
            break;
        }
    }
} catch (Exception e) {
    // If Nimbus is not available, you can set the GUI to another look and feel.
}
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbldetails = new javax.swing.JLabel();
        pnlmain = new javax.swing.JPanel();
        pnlprsnldetails = new javax.swing.JPanel();
        lblfullname = new javax.swing.JLabel();
        lblogender = new javax.swing.JLabel();
        lblphone = new javax.swing.JLabel();
        txtclass1 = new javax.swing.JComboBox();
        txtstream1 = new javax.swing.JComboBox();
        txtyear1 = new com.toedter.calendar.JYearChooser();
        pnlotherdetails = new javax.swing.JPanel();
        lblhome = new javax.swing.JLabel();
        lblemail = new javax.swing.JLabel();
        lblhome1 = new javax.swing.JLabel();
        txtterm1 = new javax.swing.JComboBox();
        txtetype1 = new javax.swing.JComboBox();
        txtsearch = new javax.swing.JTextField();
        tbpreports = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnmarksheetp = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblemail1 = new javax.swing.JLabel();
        txtadmno = new javax.swing.JTextField();
        btnpreview = new javax.swing.JButton();
        btnmarksheetp1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnpreviewanalysis = new javax.swing.JButton();
        btnpreviewanalysis1 = new javax.swing.JButton();
        btnsearch = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Examination Reports");

        lbldetails.setBackground(new java.awt.Color(153, 255, 153));
        lbldetails.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbldetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbldetails.setText("Examination Reports Preview Form");
        lbldetails.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lbldetails.setName(""); // NOI18N
        lbldetails.setOpaque(true);

        pnlmain.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        pnlprsnldetails.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblfullname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblfullname.setText(" Class");

        lblogender.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblogender.setText("Stream");

        lblphone.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblphone.setText("Year");

        txtclass1.setBackground(new java.awt.Color(255, 255, 204));
        txtclass1.setEditable(true);
        txtclass1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", " ", " " }));
        txtclass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtclass1ActionPerformed(evt);
            }
        });

        txtstream1.setBackground(new java.awt.Color(255, 255, 204));
        txtstream1.setEditable(true);
        txtstream1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "North", "South", "East", "West" }));

        txtyear1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtyear1MouseEntered(evt);
            }
        });
        txtyear1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtyear1PropertyChange(evt);
            }
        });
        txtyear1.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                txtyear1VetoableChange(evt);
            }
        });

        org.jdesktop.layout.GroupLayout pnlprsnldetailsLayout = new org.jdesktop.layout.GroupLayout(pnlprsnldetails);
        pnlprsnldetails.setLayout(pnlprsnldetailsLayout);
        pnlprsnldetailsLayout.setHorizontalGroup(
            pnlprsnldetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlprsnldetailsLayout.createSequentialGroup()
                .addContainerGap()
                .add(pnlprsnldetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(lblogender, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, lblphone, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, lblfullname, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnlprsnldetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(txtclass1, 0, 192, Short.MAX_VALUE)
                    .add(txtstream1, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(txtyear1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlprsnldetailsLayout.setVerticalGroup(
            pnlprsnldetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlprsnldetailsLayout.createSequentialGroup()
                .add(pnlprsnldetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(lblfullname, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(pnlprsnldetailsLayout.createSequentialGroup()
                        .add(6, 6, 6)
                        .add(txtclass1)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnlprsnldetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblogender, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(txtstream1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnlprsnldetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblphone, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(txtyear1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlotherdetails.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblhome.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblhome.setText("Examination Type");

        lblemail.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblemail.setText("Examination Number");

        lblhome1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblhome1.setText("Term");

        txtterm1.setBackground(new java.awt.Color(255, 255, 204));
        txtterm1.setEditable(true);
        txtterm1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3" }));

        txtetype1.setBackground(new java.awt.Color(255, 255, 204));
        txtetype1.setEditable(true);
        txtetype1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Opener Exam", "Midterm Exam", "Endterm Exam" }));
        txtetype1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtetype1ActionPerformed(evt);
            }
        });

        txtsearch.setEditable(false);
        txtsearch.setBackground(new java.awt.Color(255, 255, 204));
        txtsearch.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        org.jdesktop.layout.GroupLayout pnlotherdetailsLayout = new org.jdesktop.layout.GroupLayout(pnlotherdetails);
        pnlotherdetails.setLayout(pnlotherdetailsLayout);
        pnlotherdetailsLayout.setHorizontalGroup(
            pnlotherdetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlotherdetailsLayout.createSequentialGroup()
                .add(pnlotherdetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblemail)
                    .add(lblhome, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 122, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lblhome1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 122, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(pnlotherdetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(txtterm1, 0, 219, Short.MAX_VALUE)
                    .add(txtetype1, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(txtsearch)))
        );
        pnlotherdetailsLayout.setVerticalGroup(
            pnlotherdetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlotherdetailsLayout.createSequentialGroup()
                .add(pnlotherdetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblhome1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(pnlotherdetailsLayout.createSequentialGroup()
                        .add(4, 4, 4)
                        .add(txtterm1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnlotherdetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblhome, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(txtetype1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnlotherdetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblemail, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(txtsearch, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        tbpreports.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbpreports.setEnabled(false);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_primaryschoolmanagement_client/1372441198_Preview.png"))); // NOI18N
        jButton1.setText("Preview Marksheet Using Exam Number Parameter ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnmarksheetp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_primaryschoolmanagement_client/1372441198_Preview.png"))); // NOI18N
        btnmarksheetp.setText("Preview Marksheet For the Class");
        btnmarksheetp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmarksheetpActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jButton1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                    .add(btnmarksheetp, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(35, 35, 35)
                .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(btnmarksheetp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        tbpreports.addTab("Marksheets", jPanel1);

        lblemail1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblemail1.setText("Admission Number");

        txtadmno.setBackground(new java.awt.Color(255, 255, 204));
        txtadmno.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        btnpreview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_primaryschoolmanagement_client/1372441198_Preview.png"))); // NOI18N
        btnpreview.setText("Preview Student's Report Form");
        btnpreview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpreviewActionPerformed(evt);
            }
        });

        btnmarksheetp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_primaryschoolmanagement_client/1372441198_Preview.png"))); // NOI18N
        btnmarksheetp1.setText("Preview Report Forms For the Class");
        btnmarksheetp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmarksheetp1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(lblemail1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(txtadmno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 115, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(266, 266, 266))
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(btnmarksheetp1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                    .add(btnpreview, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblemail1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(txtadmno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(btnpreview, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(btnmarksheetp1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(22, 22, 22))
        );

        tbpreports.addTab("Report Forms", jPanel2);

        btnpreviewanalysis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_primaryschoolmanagement_client/1372441198_Preview.png"))); // NOI18N
        btnpreviewanalysis.setText("Stream Exam Analysis");
        btnpreviewanalysis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpreviewanalysisActionPerformed(evt);
            }
        });

        btnpreviewanalysis1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_primaryschoolmanagement_client/1372441198_Preview.png"))); // NOI18N
        btnpreviewanalysis1.setText("Class Exam Analysis");
        btnpreviewanalysis1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpreviewanalysis1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(btnpreviewanalysis, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 332, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btnpreviewanalysis1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 332, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .add(btnpreviewanalysis1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btnpreviewanalysis, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(56, 56, 56))
        );

        tbpreports.addTab("Exam Analysis", jPanel3);

        org.jdesktop.layout.GroupLayout pnlmainLayout = new org.jdesktop.layout.GroupLayout(pnlmain);
        pnlmain.setLayout(pnlmainLayout);
        pnlmainLayout.setHorizontalGroup(
            pnlmainLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, pnlmainLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(pnlprsnldetails, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnlotherdetails, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(pnlmainLayout.createSequentialGroup()
                .add(tbpreports, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 494, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
        );
        pnlmainLayout.setVerticalGroup(
            pnlmainLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlmainLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(pnlmainLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pnlprsnldetails, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(pnlotherdetails, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(tbpreports, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 189, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(244, 244, 244))
        );

        btnsearch.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_primaryschoolmanagement_client/1372438975_Search.png"))); // NOI18N
        btnsearch.setText("Find Exam");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(225, 225, 225)
                .add(lbldetails, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 335, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(101, 101, 101)
                .add(btnsearch, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(pnlmain, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(lbldetails, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 53, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btnsearch))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnlmain, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 457, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public static String dbusername="root";
 public  static String dbhostip;
 public  static String dbpassword;
public  static String database;  
    public static void dblogincred(){
    
        String fileName = "C:\\Users\\Public\\Documents\\dblogin.txt";

        try {
            // Use this for reading the data.
            String[] login=new String[10];
            byte[] buffer = new byte[1000];

            FileInputStream inputStream = 
                new FileInputStream(fileName);

            int total = 0;
            int nRead = 0;
            while((nRead = inputStream.read(buffer)) != -1) {
               
             login[total]= (new String(buffer));
                total += nRead;
                
            }
            if(login[1]!=null){
            dbpassword=login[1].trim();
            }
             if(login[0]!=null){
            dbhostip=login[0].trim();
            }
               inputStream.close();
               if(dbhostip.isEmpty()==false){
               int l=dbhostip.indexOf("n");
               int e=dbhostip.indexOf("%");
               
        dbpassword=dbhostip.substring(l+1,e).trim();
        database=dbhostip.substring(e+1).trim();
        dbhostip=dbhostip.substring(0, l).trim();
         System.out.println(""+dbhostip);
         System.out.println(""+database);
         System.out.println(""+dbpassword);
               }
          
        }
        catch(FileNotFoundException ex) {
            System.out.println(
                "Unable to open file '" + 
                fileName + "'");
      
        }
        catch(IOException ex) {
            System.out.println(
                "Error reading file '" 
                + fileName + "'");					
            
        }
         
    }
    
    
 

 

 
    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
        try{
        String examno = txtsearch.getText();

      Class.forName("com.mysql.jdbc.Driver");
      Connection con = DriverManager.getConnection("jdbc:mysql://"+dbhostip+":3306/myschool", dbusername, dbpassword);

      Statement st = con.createStatement();

      String sql = "Select * from exam, score where score.examno=exam.examno and exam.examno = '"+examno+"'";

      ResultSet rs = st.executeQuery(sql);
      if(rs.next()){
        JOptionPane.showMessageDialog(rootPane, "Record Found");
        tbpreports.setEnabled(true);
     
      }
      else{
        //    JOptionPane.showMessageDialog(rootPane, "Record not found please try again");
    tbpreports.setEnabled(true);
     
      }
  
    

    

    
    }
    catch (SQLException ex) {
          JOptionPane.showMessageDialog(rootPane, "Error "+ex.getMessage());
        
        ex.printStackTrace();
      } catch (ClassNotFoundException ex) {
        Logger.getLogger(examreports.class.getName()).log(Level.SEVERE, null, ex);
          JOptionPane.showMessageDialog(rootPane, "Error "+ex.getMessage());
     
    }
  
        
        
        
    }//GEN-LAST:event_btnsearchActionPerformed

    private void txtclass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtclass1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtclass1ActionPerformed

    private void txtetype1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtetype1ActionPerformed
        // TODO add your handling code here:
         String type=(String) txtetype1.getSelectedItem();
        String clas=(String) txtclass1.getSelectedItem();
        String stream=(String) txtstream1.getSelectedItem();
         String term=(String) txtterm1.getSelectedItem();
        int year=txtyear1.getYear();
         
         txtsearch.setText(""+type+"-"+clas+"-"+stream+"-"+term+"-"+year);
    }//GEN-LAST:event_txtetype1ActionPerformed

    private void txtyear1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtyear1MouseEntered
        // TODO add your handling code here:
              String type=(String) txtetype1.getSelectedItem();
        String clas=(String) txtclass1.getSelectedItem();
        String stream=(String) txtstream1.getSelectedItem();
         String term=(String) txtterm1.getSelectedItem();
        int year=txtyear1.getYear();
         
         txtsearch.setText(""+type+"-"+clas+"-"+stream+"-"+term+"-"+year);
     
    }//GEN-LAST:event_txtyear1MouseEntered

    private void txtyear1VetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_txtyear1VetoableChange
        // TODO add your handling code here:.
             String type=(String) txtetype1.getSelectedItem();
        String clas=(String) txtclass1.getSelectedItem();
        String stream=(String) txtstream1.getSelectedItem();
         String term=(String) txtterm1.getSelectedItem();
        int year=txtyear1.getYear();
         
         txtsearch.setText(""+type+"-"+clas+"-"+stream+"-"+term+"-"+year);
    }//GEN-LAST:event_txtyear1VetoableChange

    private void txtyear1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtyear1PropertyChange
        // TODO add your handling code here:
              String type=(String) txtetype1.getSelectedItem();
        String clas=(String) txtclass1.getSelectedItem();
        String stream=(String) txtstream1.getSelectedItem();
         String term=(String) txtterm1.getSelectedItem();
        int year=txtyear1.getYear();
         
         txtsearch.setText(""+type+"-"+clas+"-"+stream+"-"+term+"-"+year);
    }//GEN-LAST:event_txtyear1PropertyChange

    private void btnpreviewanalysisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpreviewanalysisActionPerformed
        // TODO add your handling code here:
   try { int ex = Integer.parseInt((String)this.txtclass1.getSelectedItem());
      int ad = this.txtyear1.getYear();
      int tr = Integer.parseInt((String)this.txtterm1.getSelectedItem());
      String type = (String)txtetype1.getSelectedItem();
      try
      {
       Class.forName("com.mysql.jdbc.Driver");
       Connection con = DriverManager.getConnection("jdbc:mysql://"+dbhostip+":3306/"+database, dbusername, dbpassword);
       Map parameters = new HashMap();
       parameters.put("examno", (txtsearch.getText()));
       
       JasperReport report = (JasperReport)JRLoader.loadObject(getClass().getResource("analyse.jasper"));
       JasperPrint jasperPrint = JasperFillManager.fillReport(report, parameters, con);
       
       JFrame frame = new JFrame("Examination Analysis");
       frame.getContentPane().add(new JRViewer(jasperPrint));
       frame.setVisible(true);
       frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
      
         
      } catch (SQLException e) {
          e.printStackTrace();
                    JOptionPane.showMessageDialog(rootPane, "Report cannot be displayed \n Error:"+e.getMessage());

      } catch (JRException ed) {
          ed.printStackTrace();
                    JOptionPane.showMessageDialog(rootPane, "Report cannot be displayed \n Error:"+ed.getMessage());

      }
    } catch (Exception exr) {
        exr.printStackTrace();
              JOptionPane.showMessageDialog(rootPane, "Report cannot be displayed \n Error:"+exr.getMessage());
    }
        
    }//GEN-LAST:event_btnpreviewanalysisActionPerformed

    private void btnpreviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpreviewActionPerformed
        // TODO add your handling code here:
    views();
    }//GEN-LAST:event_btnpreviewActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(tbpreports.isEnabled()){
        views3();
        }
        else{
            JOptionPane.showMessageDialog(rootPane,"Please find exam to see if record exists before you can proceed");
        }
      
               
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnmarksheetpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmarksheetpActionPerformed
        // TODO add your handling code here:
         if(tbpreports.isEnabled()){
        
        views4();
         }
         else{
            JOptionPane.showMessageDialog(rootPane,"Please find exam to see if record exists before you can proceed");
        }
      
    }//GEN-LAST:event_btnmarksheetpActionPerformed

    private void btnmarksheetp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmarksheetp1ActionPerformed
        // TODO add your handling code here:
        views2();
        
        
    }//GEN-LAST:event_btnmarksheetp1ActionPerformed

    private void btnpreviewanalysis1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpreviewanalysis1ActionPerformed
        // TODO add your handling code here:
         try { int ex = Integer.parseInt((String)this.txtclass1.getSelectedItem());
      int ad = this.txtyear1.getYear();
      int tr = Integer.parseInt((String)this.txtterm1.getSelectedItem());
      String type = (String)txtetype1.getSelectedItem();
      try
      {
          Class.forName("com.mysql.jdbc.Driver");
   
        Connection con = DriverManager.getConnection("jdbc:mysql://"+dbhostip+":3306/"+database, dbusername, dbpassword);
        Map parameters = new HashMap();
        parameters.put("year", (ad));
        parameters.put("class", (ex));
        parameters.put("term", (tr));
        parameters.put("type", (type));

        JasperReport report = (JasperReport)JRLoader.loadObject(getClass().getResource("classanalyse.jasper"));
        JasperPrint jasperPrint = JasperFillManager.fillReport(report, parameters, con);
        JFrame frame = new JFrame("Examination Analysis");
        frame.getContentPane().add(new JRViewer(jasperPrint));
         frame.setVisible(true);
         frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
      
         
      } catch (SQLException e) {
          e.printStackTrace();
                    JOptionPane.showMessageDialog(rootPane, "Report cannot be displayed \n Error:"+e.getMessage());

      } catch (JRException ed) {
          ed.printStackTrace();
                    JOptionPane.showMessageDialog(rootPane, "Report cannot be displayed \n Error:"+ed.getMessage());

      }
    } catch (Exception exr) {
        exr.printStackTrace();
              JOptionPane.showMessageDialog(rootPane, "Report cannot be displayed \n Error:"+exr.getMessage());
    }
    }//GEN-LAST:event_btnpreviewanalysis1ActionPerformed
      public void views() {
    try {
      String ex = txtsearch.getText();
      int ad = Integer.parseInt(this.txtadmno.getText());
      try
      {
          Class.forName("com.mysql.jdbc.Driver");
   
        Connection con = DriverManager.getConnection("jdbc:mysql://"+dbhostip+":3306/"+database, dbusername, dbpassword);
        Map parameters = new HashMap();
        parameters.put("admno", Integer.valueOf(ad));
        parameters.put("examno", ex);
        JasperReport report = (JasperReport)JRLoader.loadObject(getClass().getResource("markshet.jasper"));
        JasperPrint jasperPrint = JasperFillManager.fillReport(report, parameters, con);
        JFrame frame = new JFrame("Student Report Card");
        frame.getContentPane().add(new JRViewer(jasperPrint));
         frame.setVisible(true);
            frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
     
      } catch (SQLException e) {
          e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Report cannot be displayed \n Error:"+e.getMessage());

      } catch (JRException ed) {
          ed.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Report cannot be displayed \n Error:"+ed.getMessage());

      }
    } catch (Exception exr) {
        exr.printStackTrace();
      JOptionPane.showMessageDialog(rootPane, "Report cannot be displayed \n Error:"+exr.getMessage());
    }
  }
       public void views2() {
    try {
      try
      {
           int ex = Integer.parseInt((String)this.txtclass1.getSelectedItem());
      int ad = this.txtyear1.getYear();
      int tr = Integer.parseInt((String)this.txtterm1.getSelectedItem());
      String type = (String)txtetype1.getSelectedItem();
          Class.forName("com.mysql.jdbc.Driver");
   
        Connection con = DriverManager.getConnection("jdbc:mysql://"+dbhostip+":3306/"+database, dbusername, dbpassword);
        Map parameters = new HashMap();
        parameters.put("class",(ex));
        parameters.put("year", (ad));
        parameters.put("Term", (tr));
        parameters.put("Type", type);
        JasperReport report = (JasperReport)JRLoader.loadObject(getClass().getResource("markshet2.jasper"));
        JasperPrint jasperPrint = JasperFillManager.fillReport(report, parameters, con);
        JFrame frame = new JFrame("Student Report Card");
        frame.getContentPane().add(new JRViewer(jasperPrint));
        frame.setVisible(true);
       frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
      } catch (SQLException e) {
          e.printStackTrace();
       JOptionPane.showMessageDialog(rootPane, "Report cannot be displayed \n Error:"+e.getMessage());

          
      } catch (JRException ed) {
          ed.printStackTrace();
                    JOptionPane.showMessageDialog(rootPane, "Report cannot be displayed \n Error:"+ed.getMessage());

      }
    } catch (Exception exr) {
        exr.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Report cannot be displayed \n Error:"+exr.getMessage());
    }
  }
  public void views3() {
    try { String ex =txtsearch.getText();
      try
      {
          Class.forName("com.mysql.jdbc.Driver");
   
        Connection con = DriverManager.getConnection("jdbc:mysql://"+dbhostip+":3306/"+database, dbusername, dbpassword);
        Map parameters = new HashMap();
        parameters.put("Examno", ex);

        JasperReport report = (JasperReport)JRLoader.loadObject(getClass().getResource("markshet_3.jasper"));
        JasperPrint jasperPrint = JasperFillManager.fillReport(report, parameters, con);
        JFrame frame = new JFrame("Examination Reports");
        
        frame.getContentPane().add(new JRViewer(jasperPrint));
         
        frame.setVisible(true);
         frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
       
      } catch (SQLException e) {
          e.printStackTrace();
                    JOptionPane.showMessageDialog(rootPane, "Report cannot be displayed \n Error:"+e.getMessage());

          
      } catch (JRException ed) {
          ed.printStackTrace();
                    JOptionPane.showMessageDialog(rootPane, "Report cannot be displayed \n Error:"+ed.getMessage());

      }
    } catch (Exception exr) {
        exr.printStackTrace();
           JOptionPane.showMessageDialog(rootPane, "Report cannot be displayed \n Error:"+exr.getMessage());
    }
  }

  public void views4() {
    try { int ex = Integer.parseInt((String)this.txtclass1.getSelectedItem());
      int ad = this.txtyear1.getYear();
      int tr = Integer.parseInt((String)this.txtterm1.getSelectedItem());
      String type = (String)txtetype1.getSelectedItem();
      try
      {
          Class.forName("com.mysql.jdbc.Driver");
   
        Connection con = DriverManager.getConnection("jdbc:mysql://"+dbhostip+":3306/"+database, dbusername, dbpassword);
        Map parameters = new HashMap();
        parameters.put("year", (ad));
        parameters.put("class", (ex));
        parameters.put("term", (tr));
        parameters.put("type", (type));

        JasperReport report = (JasperReport)JRLoader.loadObject(getClass().getResource("marksheet22.jasper"));
        JasperPrint jasperPrint = JasperFillManager.fillReport(report, parameters, con);
        JFrame frame = new JFrame("Examination Reports");
        frame.getContentPane().add(new JRViewer(jasperPrint));
         frame.setVisible(true);
         frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
      
         
      } catch (SQLException e) {
          e.printStackTrace();
                    JOptionPane.showMessageDialog(rootPane, "Report cannot be displayed \n Error:"+e.getMessage());

      } catch (JRException ed) {
          ed.printStackTrace();
                    JOptionPane.showMessageDialog(rootPane, "Report cannot be displayed \n Error:"+ed.getMessage());

      }
    } catch (Exception exr) {
        exr.printStackTrace();
              JOptionPane.showMessageDialog(rootPane, "Report cannot be displayed \n Error:"+exr.getMessage());
    }
  }
  public void anlyse(){
      
     try { 
      String ex = this.txtsearch.getText();
      Class.forName("com.mysql.jdbc.Driver");
   
         Connection con = DriverManager.getConnection("jdbc:mysql://"+dbhostip+":3306/"+database, dbusername, dbpassword);
     
         
      } catch (SQLException e) {
          e.printStackTrace();
                    JOptionPane.showMessageDialog(rootPane, "Report cannot be displayed \n Error:"+e.getMessage());

      } catch (ClassNotFoundException ex) {
        Logger.getLogger(examreports.class.getName()).log(Level.SEVERE, null, ex);
     }
    
      
      
  }
  
  
  
  
  
  
  
  
    public static String points(int mark)
  {
    if ((mark > 0) && (mark <= 1)) {
      return "E";
    }
    if ((mark > 0) && (mark <= 1))
      return "E";
    if ((mark > 1) && (mark <= 2))
      return "D-";
    if ((mark > 2) && (mark <= 3))
      return "D";
    if ((mark > 3) && (mark <= 4))
      return "D+";
    if ((mark > 4) && (mark <= 5))
      return "C-";
    if ((mark > 5) && (mark <= 6))
      return "C";
    if ((mark > 6) && (mark <= 7))
      return "C+";
    if ((mark > 7) && (mark <= 8))
      return "B-";
    if ((mark > 8) && (mark <= 9))
      return "B";
    if ((mark > 9) && (mark <= 10))
      return "B+";
    if ((mark > 10) && (mark <= 11))
      return "A-";
    if ((mark > 11) && (mark <= 12)) {
      return "A";
    }

    return "X"; } 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnmarksheetp;
    private javax.swing.JButton btnmarksheetp1;
    private javax.swing.JButton btnpreview;
    private javax.swing.JButton btnpreviewanalysis;
    private javax.swing.JButton btnpreviewanalysis1;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbldetails;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblemail1;
    private javax.swing.JLabel lblfullname;
    private javax.swing.JLabel lblhome;
    private javax.swing.JLabel lblhome1;
    private javax.swing.JLabel lblogender;
    private javax.swing.JLabel lblphone;
    private javax.swing.JPanel pnlmain;
    private javax.swing.JPanel pnlotherdetails;
    private javax.swing.JPanel pnlprsnldetails;
    private javax.swing.JTabbedPane tbpreports;
    private javax.swing.JTextField txtadmno;
    private javax.swing.JComboBox txtclass1;
    private javax.swing.JComboBox txtetype1;
    private javax.swing.JTextField txtsearch;
    private javax.swing.JComboBox txtstream1;
    private javax.swing.JComboBox txtterm1;
    private com.toedter.calendar.JYearChooser txtyear1;
    // End of variables declaration//GEN-END:variables
}
