/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package g_primaryschoolmanagement_client;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author Griffin M
 */
public class main extends javax.swing.JFrame {
public String dbusername="root";

  public String dbhostip;
    public String dbpassword;
    public String database;
    /**
     * Creates new form main
     */
  

    public main() {
         
        initComponents();
           dblogincred();
         welcome();
       
        schooldetails();

      
    
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblschool = new javax.swing.JLabel();
        lbllogo = new javax.swing.JLabel();
        lblcuser = new javax.swing.JLabel();
        pnluser = new javax.swing.JPanel();
        lblusername = new javax.swing.JLabel();
        txtusername = new javax.swing.JLabel();
        lblfullname = new javax.swing.JLabel();
        txtfullname = new javax.swing.JLabel();
        lblstatus = new javax.swing.JLabel();
        txtstatus = new javax.swing.JLabel();
        btnmessages = new javax.swing.JButton();
        btnadd = new javax.swing.JButton();
        lblstatus1 = new javax.swing.JLabel();
        txtcredentials = new javax.swing.JLabel();
        lblfooter = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        home = new javax.swing.JMenu();
        messagesMenu = new javax.swing.JMenu();
        jMenuItemreadmessages = new javax.swing.JMenuItem();
        jMenuItemcomposemessage = new javax.swing.JMenuItem();
        newMenuItem = new javax.swing.JMenuItem();
        logoutMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        adminmenu = new javax.swing.JMenu();
        stddetailsMenuItem = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        classlistmenuitem = new javax.swing.JMenuItem();
        examinationmenu = new javax.swing.JMenu();
        examsmenuitem = new javax.swing.JMenuItem();
        examreportsmenuitem = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        financemenu = new javax.swing.JMenu();
        feesstructuremenuitem = new javax.swing.JMenuItem();
        feespaymentmenuitem = new javax.swing.JMenuItem();
        feesrecordsmenuitem = new javax.swing.JMenuItem();
        boardingmenu = new javax.swing.JMenu();
        dormitoriesmenuitem = new javax.swing.JMenuItem();
        gamesmenu = new javax.swing.JMenu();
        gamescalendermenuitem = new javax.swing.JMenuItem();
        helpmenu = new javax.swing.JMenu();
        usermanualmenuitem = new javax.swing.JMenuItem();
        contentMenuItem = new javax.swing.JMenuItem();
        morehelpmenuitem = new javax.swing.JMenuItem();
        aboutmenu = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("The Primary School Manager");
        setIconImages(null);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Gabriola", 2, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_primaryschoolmanagement_client/Fullscreen capture 5152013 115827 AM.bmp.jpg"))); // NOI18N
        jLabel1.setText("Developed by G Ultimate Developers  :-  Griffin");

        jLabel2.setFont(new java.awt.Font("Gabriola", 2, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_primaryschoolmanagement_client/hslogo.jpg"))); // NOI18N
        jLabel2.setText("The G_PrimarySchool Manager");

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblschool.setBackground(new java.awt.Color(153, 153, 255));
        lblschool.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        lblschool.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblschool.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblschool.setOpaque(true);

        lbllogo.setBackground(new java.awt.Color(153, 153, 255));
        lbllogo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbllogo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(lblschool, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbllogo, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(181, 181, 181))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblschool, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(lbllogo, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        lblcuser.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        pnluser.setOpaque(false);

        lblusername.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblusername.setForeground(new java.awt.Color(153, 0, 153));
        lblusername.setText("Username:");

        txtusername.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtusername.setForeground(new java.awt.Color(153, 0, 153));
        txtusername.setOpaque(true);

        lblfullname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblfullname.setForeground(new java.awt.Color(153, 0, 153));
        lblfullname.setText("Fullname:");

        txtfullname.setBackground(new java.awt.Color(204, 204, 204));
        txtfullname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtfullname.setForeground(new java.awt.Color(153, 0, 153));
        txtfullname.setOpaque(true);

        lblstatus.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblstatus.setForeground(new java.awt.Color(153, 0, 153));
        lblstatus.setText("Status:");

        txtstatus.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtstatus.setForeground(new java.awt.Color(153, 0, 153));
        txtstatus.setOpaque(true);

        btnmessages.setBackground(new java.awt.Color(102, 0, 102));
        btnmessages.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnmessages.setText("Messages");
        btnmessages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmessagesActionPerformed(evt);
            }
        });

        btnadd.setText("Add Users");
        btnadd.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnadd.setEnabled(false);
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        lblstatus1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblstatus1.setForeground(new java.awt.Color(153, 0, 153));
        lblstatus1.setText("Credentials:");

        txtcredentials.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtcredentials.setForeground(new java.awt.Color(153, 0, 153));
        txtcredentials.setOpaque(true);

        javax.swing.GroupLayout pnluserLayout = new javax.swing.GroupLayout(pnluser);
        pnluser.setLayout(pnluserLayout);
        pnluserLayout.setHorizontalGroup(
            pnluserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblusername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtusername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblfullname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtfullname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblstatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtstatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnmessages, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnadd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblstatus1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtcredentials, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnluserLayout.setVerticalGroup(
            pnluserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnluserLayout.createSequentialGroup()
                .addComponent(lblusername, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblfullname, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtfullname, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblstatus1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtcredentials, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnadd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnmessages)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnluser, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblcuser, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                    .addComponent(lblcuser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnluser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.setBounds(80, 0, 910, 640);
        desktopPane.add(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblfooter.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblfooter.setForeground(new java.awt.Color(102, 0, 102));
        lblfooter.setText("G Ultimate Developers:2013 All Rights Reserved");
        lblfooter.setBounds(400, 660, 280, 17);
        desktopPane.add(lblfooter, javax.swing.JLayeredPane.DEFAULT_LAYER);

        menuBar.setBackground(new java.awt.Color(102, 0, 102));

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_primaryschoolmanagement_client/home.png"))); // NOI18N
        home.setMnemonic('f');
        home.setText("Home");
        home.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        messagesMenu.setText("Messages");

        jMenuItemreadmessages.setText("Read Messages");
        jMenuItemreadmessages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemreadmessagesActionPerformed(evt);
            }
        });
        messagesMenu.add(jMenuItemreadmessages);

        jMenuItemcomposemessage.setText("Compose Message");
        jMenuItemcomposemessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemcomposemessageActionPerformed(evt);
            }
        });
        messagesMenu.add(jMenuItemcomposemessage);

        home.add(messagesMenu);

        newMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_primaryschoolmanagement_client/1372431829_Add-Male-User.png"))); // NOI18N
        newMenuItem.setMnemonic('s');
        newMenuItem.setText("New User");
        newMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newMenuItemActionPerformed(evt);
            }
        });
        home.add(newMenuItem);

        logoutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_primaryschoolmanagement_client/1372431837_logout.png"))); // NOI18N
        logoutMenuItem.setMnemonic('a');
        logoutMenuItem.setText("Logout");
        logoutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutMenuItemActionPerformed(evt);
            }
        });
        home.add(logoutMenuItem);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        exitMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_primaryschoolmanagement_client/1372431837_exit.png"))); // NOI18N
        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        home.add(exitMenuItem);

        menuBar.add(home);

        adminmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_primaryschoolmanagement_client/home (2).png"))); // NOI18N
        adminmenu.setMnemonic('e');
        adminmenu.setText("Administration");
        adminmenu.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        stddetailsMenuItem.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        stddetailsMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_primaryschoolmanagement_client/1372264978_Student_3D.png"))); // NOI18N
        stddetailsMenuItem.setMnemonic('t');
        stddetailsMenuItem.setText("Student Details");
        stddetailsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stddetailsMenuItemActionPerformed(evt);
            }
        });
        adminmenu.add(stddetailsMenuItem);

        jMenuItem1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_primaryschoolmanagement_client/1372265014_group.png"))); // NOI18N
        jMenuItem1.setText("Parent Details");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        adminmenu.add(jMenuItem1);

        classlistmenuitem.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        classlistmenuitem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_primaryschoolmanagement_client/1372265104_stock_data-tables.png"))); // NOI18N
        classlistmenuitem.setText("Class List");
        classlistmenuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classlistmenuitemActionPerformed(evt);
            }
        });
        adminmenu.add(classlistmenuitem);

        menuBar.add(adminmenu);

        examinationmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_primaryschoolmanagement_client/edit (2).png"))); // NOI18N
        examinationmenu.setText("Examination");
        examinationmenu.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        examsmenuitem.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        examsmenuitem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_primaryschoolmanagement_client/1372265104_stock_data-tables.png"))); // NOI18N
        examsmenuitem.setText("Exams Data Entry");
        examsmenuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examsmenuitemActionPerformed(evt);
            }
        });
        examinationmenu.add(examsmenuitem);

        examreportsmenuitem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_primaryschoolmanagement_client/1372431943_reports.png"))); // NOI18N
        examreportsmenuitem.setText("Examination Reports");
        examreportsmenuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examreportsmenuitemActionPerformed(evt);
            }
        });
        examinationmenu.add(examreportsmenuitem);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_primaryschoolmanagement_client/1372441198_Preview.png"))); // NOI18N
        jMenuItem3.setText("Search  Records");
        jMenuItem3.setActionCommand("");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        examinationmenu.add(jMenuItem3);

        menuBar.add(examinationmenu);
        examinationmenu.getAccessibleContext().setAccessibleName("");

        financemenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_primaryschoolmanagement_client/1372264460_finance.png"))); // NOI18N
        financemenu.setText("Finance");
        financemenu.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        feesstructuremenuitem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_primaryschoolmanagement_client/1372431892_cheque.png"))); // NOI18N
        feesstructuremenuitem.setText("Fees Structure");
        feesstructuremenuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feesstructuremenuitemActionPerformed(evt);
            }
        });
        financemenu.add(feesstructuremenuitem);

        feespaymentmenuitem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_primaryschoolmanagement_client/1372445808_Money.png"))); // NOI18N
        feespaymentmenuitem.setText("Fees Payment");
        feespaymentmenuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feespaymentmenuitemActionPerformed(evt);
            }
        });
        financemenu.add(feespaymentmenuitem);

        feesrecordsmenuitem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_primaryschoolmanagement_client/1372438975_Search.png"))); // NOI18N
        feesrecordsmenuitem.setText("Search Fees Records");
        feesrecordsmenuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feesrecordsmenuitemActionPerformed(evt);
            }
        });
        financemenu.add(feesrecordsmenuitem);

        menuBar.add(financemenu);

        boardingmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_primaryschoolmanagement_client/1372264500_hostel.png"))); // NOI18N
        boardingmenu.setText("Boarding");
        boardingmenu.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        dormitoriesmenuitem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_primaryschoolmanagement_client/1372431840_university.png"))); // NOI18N
        dormitoriesmenuitem.setText("Dormitories");
        dormitoriesmenuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dormitoriesmenuitemActionPerformed(evt);
            }
        });
        boardingmenu.add(dormitoriesmenuitem);

        menuBar.add(boardingmenu);

        gamesmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_primaryschoolmanagement_client/1372264542_Soccer_Ball.png"))); // NOI18N
        gamesmenu.setText("Games");
        gamesmenu.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        gamescalendermenuitem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_primaryschoolmanagement_client/1372431994_calendar.png"))); // NOI18N
        gamescalendermenuitem.setText("Games Calendar");
        gamescalendermenuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gamescalendermenuitemActionPerformed(evt);
            }
        });
        gamesmenu.add(gamescalendermenuitem);

        menuBar.add(gamesmenu);

        helpmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_primaryschoolmanagement_client/help.png"))); // NOI18N
        helpmenu.setText("Help");
        helpmenu.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        usermanualmenuitem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_primaryschoolmanagement_client/1372432105_preferences-desktop-personal.png"))); // NOI18N
        usermanualmenuitem.setText("User Manual");
        usermanualmenuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usermanualmenuitemActionPerformed(evt);
            }
        });
        helpmenu.add(usermanualmenuitem);

        contentMenuItem.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contact Admin");
        contentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentMenuItemActionPerformed(evt);
            }
        });
        helpmenu.add(contentMenuItem);

        morehelpmenuitem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_primaryschoolmanagement_client/1372432139_system-help.png"))); // NOI18N
        morehelpmenuitem.setText("More Help..");
        morehelpmenuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                morehelpmenuitemActionPerformed(evt);
            }
        });
        helpmenu.add(morehelpmenuitem);

        menuBar.add(helpmenu);

        aboutmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_primaryschoolmanagement_client/1372264574_Orange forum.png"))); // NOI18N
        aboutmenu.setText("About");
        aboutmenu.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        aboutmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutmenuActionPerformed(evt);
            }
        });

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_primaryschoolmanagement_client/1372432139_system-help.png"))); // NOI18N
        jMenuItem2.setText("About");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        aboutmenu.add(jMenuItem2);

        menuBar.add(aboutmenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public static void reply(){
          compose cm = new compose();
        desktopPane.add(cm);
        int h = cm.getHeight();
        int w = cm.getWidth();
        cm.setBounds(250, 120, w, h);
        cm.setVisible(true);
    }
    
    public void welcome() {
        welcome wl = new welcome();
        desktopPane.add(wl);
        int h = wl.getHeight();
        int w = wl.getWidth();
        wl.setBounds(230, 150, w, h);
        wl.setVisible(true);


    }

       public void dblogincred(){
          
        String fileName = "C:\\Users\\Public\\Documents\\dblogin.txt";

        try {
            // Use this for reading the data.
            String[] login=new String[10];
            byte[] buffer = new byte[1000];

            FileInputStream inputStream = 
                new FileInputStream(fileName);

            int total = 0;
            int nRead = 0;
            while((nRead = inputStream.read(buffer)) != -1) {
               
             login[total]= (new String(buffer));
                total += nRead;
                
            }
            if(login[1]!=null){
            dbpassword=login[1].trim();
            }
             if(login[0]!=null){
            dbhostip=login[0].trim();
            }
               inputStream.close();
               int l=dbhostip.indexOf("n");
               int e=dbhostip.indexOf("%");
        dbpassword=dbhostip.substring(l+1,e).trim();
        database=dbhostip.substring(e+1).trim();
        dbhostip=dbhostip.substring(0, l).trim();
         System.out.println(""+dbhostip);
         System.out.println(""+database);
         System.out.println(""+dbpassword);
     
          
        }
        catch(FileNotFoundException ex) {
            System.out.println(
                "Unable to open file '" + 
                fileName + "'");				
        }
        catch(IOException ex) {
            System.out.println(
                "Error reading file '" 
                + fileName + "'");					
            // Or we could just do this: 
            // ex.printStackTrace();
        }
    }
    public void schooldetails(){
        
     {
    try {
        Class.forName("com.mysql.jdbc.Driver");
   
       String host = "jdbc:mysql://"+dbhostip+":3306/"+database;
      String user = dbusername;
      String password = dbpassword;
      Connection con = DriverManager.getConnection(host, user, password);
      Statement st = con.createStatement();
      ResultSet rs = st.executeQuery("Select * from school");
      rs.next();
      String name = rs.getString("sname");
    String pic=rs.getString("scpic");
    
    if((pic)!=null){
      lblschool.setText(""+name);
      
      ImageIcon spic = new ImageIcon(pic);
      Image sp = spic.getImage();
      Image resizedImage = sp.getScaledInstance(lbllogo.getWidth(), lbllogo.getHeight(), 0);
      ImageIcon rim = new ImageIcon(resizedImage);
      lbllogo.setIcon(rim);
    }
      desktopPane.setToolTipText("Welcome please login to proceed");
      } 
    catch (SQLException ex) {
      ex.printStackTrace();
       
    }    catch (ClassNotFoundException ex) {
             Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
         }
  }   
    }
    
    public static void disablemenus(){
       adminmenu.disable();
       examinationmenu.disable();
       boardingmenu.disable();
       financemenu.disable();
       gamesmenu.disable();
       
    }
    public static  void enableadmin(){
      adminmenu.enable();
      
        
    }
     public static void enableexamination(){
      examinationmenu.enable();
      
        
    }
     public static void enableboarding(){
         boardingmenu.enable();
     }
     
     public static void enablefinance(){
         financemenu.enable();
         
     }
    public static void enablegames(){
        gamesmenu.enable();
    }
    
    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
       
       int s = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to Exit?", "Exit", 0);
        if (s == 0) {
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con;
                con = DriverManager.getConnection("jdbc:mysql://" + dbhostip + ":3306/"+database, "root", dbpassword);
                PreparedStatement st = con.prepareStatement("UPDATE users SET status=? where username=?");
                st.setString(1, "offline");
                st.setString(2, txtusername.getText());
                st.executeUpdate();
                txtusername.setText("");
                txtfullname.setText("");
                txtstatus.setText("offline");
                txtstatus.setForeground(Color.black);
                JOptionPane.showMessageDialog(rootPane, "Goodbye");
                System.exit(0);

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
            }}
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void stddetailsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stddetailsMenuItemActionPerformed
        // TODO add your handling code here:
        
         student st=new student();
        desktopPane.add(st);
        st.setVisible(true);
    }//GEN-LAST:event_stddetailsMenuItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        parent pr = new parent();
        desktopPane.add(pr);
        pr.setVisible(true);
        
      
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void examsmenuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examsmenuitemActionPerformed
        // TODO add your handling code here:
        exams ex=new exams();
        desktopPane.add(ex);
        ex.setVisible(true);
        
    }//GEN-LAST:event_examsmenuitemActionPerformed

    private void dormitoriesmenuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dormitoriesmenuitemActionPerformed
        // TODO add your handling code here:
        dormitories dr=new dormitories();
        desktopPane.add(dr);
        dr.setVisible(true);
    }//GEN-LAST:event_dormitoriesmenuitemActionPerformed

    private void newMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMenuItemActionPerformed
        // TODO add your handling code here:
        newuser nu =new newuser();
        desktopPane.add(nu);
        nu.setVisible(true);
        
   
    }//GEN-LAST:event_newMenuItemActionPerformed

    private void logoutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutMenuItemActionPerformed
        // TODO add your handling code here:
         int s = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to logout?", "Logout", 0);
        if (s == 0) {
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con;
                con = DriverManager.getConnection("jdbc:mysql://" + dbhostip + ":3306/"+database, "root", dbpassword);
                PreparedStatement st = con.prepareStatement("UPDATE users SET status=? where username=?");
                st.setString(1, "offline");
                st.setString(2, txtusername.getText());
                st.executeUpdate();
                txtusername.setText("");
                txtfullname.setText("");
                txtstatus.setText("offline");
                txtstatus.setForeground(Color.black);
                JOptionPane.showMessageDialog(rootPane, "Goodbye");
                lblcuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
            disablemenus();
           main.btnadd.setEnabled(false);
       

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
            }

        
            
   
        } 
    }//GEN-LAST:event_logoutMenuItemActionPerformed

    private void feespaymentmenuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feespaymentmenuitemActionPerformed
        // TODO add your handling code here:
     feespayment fp =new feespayment();
     desktopPane.add(fp);
     fp.setVisible(true);
     

    }//GEN-LAST:event_feespaymentmenuitemActionPerformed

    private void examreportsmenuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examreportsmenuitemActionPerformed
        // TODO add your handling code here:
        examreports er=new examreports();
        desktopPane.add(er);
        er.setVisible(true);
        
    }//GEN-LAST:event_examreportsmenuitemActionPerformed

    private void feesstructuremenuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feesstructuremenuitemActionPerformed
        // TODO add your handling code here:
       feesstructure fs =new feesstructure();
       desktopPane.add(fs);
       fs.setVisible(true);
               
    }//GEN-LAST:event_feesstructuremenuitemActionPerformed

    private void gamescalendermenuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gamescalendermenuitemActionPerformed
        // TODO add your handling code here:
        games gc =new games();
        desktopPane.add(gc);
        gc.setVisible(true);
        
    }//GEN-LAST:event_gamescalendermenuitemActionPerformed

    private void aboutmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutmenuActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_aboutmenuActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
         about ab =new about();
        desktopPane.add(ab);
        ab.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void morehelpmenuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_morehelpmenuitemActionPerformed
        // TODO add your handling code here:
        morehelp mh= new morehelp();
        desktopPane.add(mh);
        mh.setVisible(true);
        
    }//GEN-LAST:event_morehelpmenuitemActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        search sr= new search();
        desktopPane.add(sr);
        sr.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        define df = new define();
        desktopPane.add(df);
        df.setVisible(true);
    }//GEN-LAST:event_btnaddActionPerformed

    private void usermanualmenuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usermanualmenuitemActionPerformed
        // TODO add your handling code here:
          
    if (Desktop.isDesktopSupported()) {
   try {
         File input=new File("C://Program Files/usermanual.pdf");
          
            Desktop.getDesktop().open(input);
        } catch (IOException ex) {
            ex.printStackTrace();
            System.out.println("NO PDF READER INSTALLED");
        }
}
  
        
    }//GEN-LAST:event_usermanualmenuitemActionPerformed

    private void btnmessagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmessagesActionPerformed
        // TODO add your handling code here:
        readmessages rm = new readmessages();
        desktopPane.add(rm);
        int h = rm.getHeight();
        int w = rm.getWidth();
        rm.setBounds(230, 150, w, h);
        rm.setVisible(true);

    }//GEN-LAST:event_btnmessagesActionPerformed

    private void jMenuItemreadmessagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemreadmessagesActionPerformed
        // TODO add your handling code here:
        readmessages wl = new readmessages();
        desktopPane.add(wl);
        int h = wl.getHeight();
        int w = wl.getWidth();
        wl.setBounds(230, 150, w, h);
        wl.setVisible(true);
    }//GEN-LAST:event_jMenuItemreadmessagesActionPerformed

    private void jMenuItemcomposemessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemcomposemessageActionPerformed
        // TODO add your handling code here:
        compose wl = new compose();
        desktopPane.add(wl);
        int h = wl.getHeight();
        int w = wl.getWidth();
        wl.setBounds(230, 150, w, h);
        wl.setVisible(true);
    }//GEN-LAST:event_jMenuItemcomposemessageActionPerformed

    private void contentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentMenuItemActionPerformed
        // TODO add your handling code here:
        compose wl = new compose();
        desktopPane.add(wl);
        int h = wl.getHeight();
        int w = wl.getWidth();
        wl.setBounds(230, 150, w, h);
        wl.setVisible(true);
    }//GEN-LAST:event_contentMenuItemActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
         int s = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to Exit?", "Exit", 0);
        if (s == 0) {
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con;
                con = DriverManager.getConnection("jdbc:mysql://" + dbhostip + ":3306/"+database, "root", dbpassword);
                PreparedStatement st = con.prepareStatement("UPDATE users SET status=? where username=?");
                st.setString(1, "offline");
                st.setString(2, txtusername.getText());
                st.executeUpdate();
                txtusername.setText("");
                txtfullname.setText("");
                txtstatus.setText("offline");
                txtstatus.setForeground(Color.black);
                JOptionPane.showMessageDialog(rootPane, "Goodbye");
                System.exit(0);

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
            }}
    }//GEN-LAST:event_formWindowClosing

    private void feesrecordsmenuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feesrecordsmenuitemActionPerformed

        feesrecords er=new feesrecords();
        desktopPane.add(er);
        //   er.setMaximum(true);
        er.setVisible(true);

    }//GEN-LAST:event_feesrecordsmenuitemActionPerformed

    private void classlistmenuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classlistmenuitemActionPerformed
        // TODO add your handling code here:
            
        String clas =JOptionPane.showInputDialog(rootPane,"Please Input the class you wish to preview classlist for e.g. 1 for Class One");
        String stream =JOptionPane.showInputDialog(rootPane,"Please Input the stream of the class you wish to preview classlist");
        JOptionPane.showMessageDialog(rootPane,"Generating class list");
              try {
      try
      {
  
          Class.forName("com.mysql.jdbc.Driver");
   
        Connection con =  DriverManager.getConnection("jdbc:mysql://"+dbhostip+":3306/"+database, dbusername, dbpassword);
        Map parameters = new HashMap();
            parameters.put("class",(clas));
       parameters.put("stream",(stream));
       
        JasperReport report = (JasperReport)JRLoader.loadObject(getClass().getResource("classlist.jasper"));
        JasperPrint jasperPrint = JasperFillManager.fillReport(report, parameters, con);
        JFrame frame = new JFrame("Class List");
        frame.getContentPane().add(new JRViewer(jasperPrint));
        frame.setVisible(true);
       frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
      } catch (SQLException e) {
          e.printStackTrace();
       JOptionPane.showMessageDialog(rootPane, "Report cannot be displayed \n Error:"+e.getMessage());

          
     
      }
    } catch (Exception exr) {
        exr.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Report cannot be displayed \n Error:"+exr.getMessage());
    }
    
        
    }//GEN-LAST:event_classlistmenuitemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
    for (LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
            UIManager.setLookAndFeel(info.getClassName());
            break;
        }
    }
} catch (Exception e) {
    // If Nimbus is not available, you can set the GUI to another look and feel.
}
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JMenu aboutmenu;
    public static javax.swing.JMenu adminmenu;
    public static javax.swing.JMenu boardingmenu;
    public static javax.swing.JButton btnadd;
    private javax.swing.JButton btnmessages;
    private javax.swing.JMenuItem classlistmenuitem;
    private javax.swing.JMenuItem contentMenuItem;
    public static javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem dormitoriesmenuitem;
    public static javax.swing.JMenu examinationmenu;
    private javax.swing.JMenuItem examreportsmenuitem;
    private javax.swing.JMenuItem examsmenuitem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenuItem feespaymentmenuitem;
    private javax.swing.JMenuItem feesrecordsmenuitem;
    private javax.swing.JMenuItem feesstructuremenuitem;
    public static javax.swing.JMenu financemenu;
    private javax.swing.JMenuItem gamescalendermenuitem;
    public static javax.swing.JMenu gamesmenu;
    public static javax.swing.JMenu helpmenu;
    public static javax.swing.JMenu home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemcomposemessage;
    private javax.swing.JMenuItem jMenuItemreadmessages;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JLabel lblcuser;
    private javax.swing.JLabel lblfooter;
    private javax.swing.JLabel lblfullname;
    private javax.swing.JLabel lbllogo;
    private javax.swing.JLabel lblschool;
    private javax.swing.JLabel lblstatus;
    private javax.swing.JLabel lblstatus1;
    private javax.swing.JLabel lblusername;
    private javax.swing.JMenuItem logoutMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu messagesMenu;
    private javax.swing.JMenuItem morehelpmenuitem;
    private javax.swing.JMenuItem newMenuItem;
    public static javax.swing.JPanel pnluser;
    private javax.swing.JMenuItem stddetailsMenuItem;
    public static javax.swing.JLabel txtcredentials;
    public static javax.swing.JLabel txtfullname;
    public static javax.swing.JLabel txtstatus;
    public static javax.swing.JLabel txtusername;
    private javax.swing.JMenuItem usermanualmenuitem;
    // End of variables declaration//GEN-END:variables
}
