/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * student.java
 *
 * Created on Jun 9, 2013, 1:38:14 PM
 */
package g_primaryschoolmanagement_client;

import java.awt.Image;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.UIManager;

import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author griffin
 */
public class student extends javax.swing.JInternalFrame {
    private String path;
    main mn;
     public student(main nm) {
        initComponents();
         this.mn=nm;
     }
    /** Creates new form student */
    public student() {
        initComponents();
          dblogincred();
        try {
    for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
            UIManager.setLookAndFeel(info.getClassName());
            break;
        }
    }
} catch (Exception e) {
    // If Nimbus is not available, you can set the GUI to another look and feel.
}
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbldetails = new javax.swing.JLabel();
        pnlmain = new javax.swing.JPanel();
        pnlprsnldetails = new javax.swing.JPanel();
        lblpic = new javax.swing.JLabel();
        lbladm = new javax.swing.JLabel();
        lblfullname = new javax.swing.JLabel();
        lblbcert = new javax.swing.JLabel();
        lbldob = new javax.swing.JLabel();
        lblsex = new javax.swing.JLabel();
        lblreligion = new javax.swing.JLabel();
        lblppic = new javax.swing.JLabel();
        txtstdadm = new javax.swing.JTextField();
        txtstdfname = new javax.swing.JTextField();
        txtbcn = new javax.swing.JTextField();
        btnbrowse = new javax.swing.JButton();
        txtdob = new com.toedter.calendar.JDateChooser();
        txtreligion = new javax.swing.JComboBox();
        txtgender = new javax.swing.JComboBox();
        pnlotherdetails = new javax.swing.JPanel();
        txtcclass = new javax.swing.JTextField();
        txtkcpe = new javax.swing.JTextField();
        lblclass = new javax.swing.JLabel();
        lblkcpe = new javax.swing.JLabel();
        lbldoa = new javax.swing.JLabel();
        lblreligion1 = new javax.swing.JLabel();
        lblcclass = new javax.swing.JLabel();
        txthouse = new javax.swing.JTextField();
        lblstream = new javax.swing.JLabel();
        txtfamily = new javax.swing.JTextField();
        lblreligion2 = new javax.swing.JLabel();
        lblsex2 = new javax.swing.JLabel();
        lbldob2 = new javax.swing.JLabel();
        lblbcert2 = new javax.swing.JLabel();
        txtdoa = new com.toedter.calendar.JDateChooser();
        txtclass = new javax.swing.JComboBox();
        txtstream = new javax.swing.JComboBox();
        txtsport = new javax.swing.JComboBox();
        txtclub = new javax.swing.JComboBox();
        txtsociety = new javax.swing.JComboBox();
        lblreligion3 = new javax.swing.JLabel();
        txtpid = new javax.swing.JTextField();
        btnsearch = new javax.swing.JButton();
        txtsearch = new javax.swing.JTextField();
        btnnewrecord = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Student Details Form");

        lbldetails.setBackground(new java.awt.Color(153, 255, 153));
        lbldetails.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbldetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbldetails.setText("Student Details Data Entry Form");
        lbldetails.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lbldetails.setName(""); // NOI18N
        lbldetails.setOpaque(true);

        pnlmain.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        pnlprsnldetails.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblpic.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblpic.setText("Student Picture");
        lblpic.setToolTipText("");

        lbladm.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbladm.setText("Student Admission");

        lblfullname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblfullname.setText("Full Name");

        lblbcert.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblbcert.setText("Birth Certificate/Number");

        lbldob.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbldob.setText("Student DOB");

        lblsex.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblsex.setText("Gender");

        lblreligion.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblreligion.setText("Religion");

        lblppic.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        txtstdadm.setBackground(new java.awt.Color(255, 255, 204));
        txtstdadm.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        txtstdfname.setBackground(new java.awt.Color(255, 255, 204));
        txtstdfname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        txtbcn.setBackground(new java.awt.Color(255, 255, 204));
        txtbcn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        btnbrowse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_primaryschoolmanagement_client/1372271867_folder_upload.png"))); // NOI18N
        btnbrowse.setText("Select");
        btnbrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbrowseActionPerformed(evt);
            }
        });

        txtdob.setBackground(new java.awt.Color(255, 255, 204));
        txtdob.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtreligion.setBackground(new java.awt.Color(255, 255, 204));
        txtreligion.setEditable(true);
        txtreligion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Christian", "Muslim" }));

        txtgender.setBackground(new java.awt.Color(255, 255, 204));
        txtgender.setEditable(true);
        txtgender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        org.jdesktop.layout.GroupLayout pnlprsnldetailsLayout = new org.jdesktop.layout.GroupLayout(pnlprsnldetails);
        pnlprsnldetails.setLayout(pnlprsnldetailsLayout);
        pnlprsnldetailsLayout.setHorizontalGroup(
            pnlprsnldetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlprsnldetailsLayout.createSequentialGroup()
                .addContainerGap()
                .add(pnlprsnldetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(lblbcert, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, lblreligion, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, lblsex, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, lbldob, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, lblfullname, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, lbladm, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, lblpic, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnlprsnldetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(txtstdadm)
                    .add(txtstdfname)
                    .add(txtbcn)
                    .add(txtdob, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(pnlprsnldetailsLayout.createSequentialGroup()
                        .add(pnlprsnldetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(btnbrowse, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 110, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(lblppic, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 185, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(0, 42, Short.MAX_VALUE))
                    .add(txtreligion, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, txtgender, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlprsnldetailsLayout.setVerticalGroup(
            pnlprsnldetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlprsnldetailsLayout.createSequentialGroup()
                .add(pnlprsnldetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblpic)
                    .add(btnbrowse, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(lblppic, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 127, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnlprsnldetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(lbladm, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .add(txtstdadm))
                .add(7, 7, 7)
                .add(pnlprsnldetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(txtstdfname)
                    .add(lblfullname, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnlprsnldetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(txtbcn)
                    .add(lblbcert, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(pnlprsnldetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(lbldob, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .add(txtdob, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(pnlprsnldetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pnlprsnldetailsLayout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(lblsex, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(lblreligion, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                        .add(17, 17, 17))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, pnlprsnldetailsLayout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(txtgender, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(txtreligion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pnlotherdetails.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txtcclass.setBackground(new java.awt.Color(255, 255, 204));
        txtcclass.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        txtkcpe.setBackground(new java.awt.Color(255, 255, 204));
        txtkcpe.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lblclass.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblclass.setText("Class Admitted");

        lblkcpe.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblkcpe.setText("KCPE Entry Admission");

        lbldoa.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbldoa.setText("Student DOA");

        lblreligion1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblreligion1.setText("House");

        lblcclass.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblcclass.setText("Current Class");

        txthouse.setBackground(new java.awt.Color(255, 255, 204));
        txthouse.setToolTipText("");
        txthouse.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lblstream.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblstream.setText("Stream Admitted");

        txtfamily.setBackground(new java.awt.Color(255, 255, 204));
        txtfamily.setToolTipText("");
        txtfamily.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lblreligion2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblreligion2.setText("Family Group");

        lblsex2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblsex2.setText("Society ");

        lbldob2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbldob2.setText("Club");

        lblbcert2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblbcert2.setText("Sport");

        txtdoa.setBackground(new java.awt.Color(255, 255, 204));
        txtdoa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtclass.setBackground(new java.awt.Color(255, 255, 204));
        txtclass.setEditable(true);
        txtclass.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8" }));
        txtclass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtclassActionPerformed(evt);
            }
        });

        txtstream.setBackground(new java.awt.Color(255, 255, 204));
        txtstream.setEditable(true);
        txtstream.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "North", "South", "East", "West" }));

        txtsport.setBackground(new java.awt.Color(255, 255, 204));
        txtsport.setEditable(true);
        txtsport.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Foot Ball", "Volley Ball", "Basket Ball", "Hockey", "Athletic" }));

        txtclub.setBackground(new java.awt.Color(255, 255, 204));
        txtclub.setEditable(true);
        txtclub.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Debate", "Drama", "Music", "Scouts" }));

        txtsociety.setBackground(new java.awt.Color(255, 255, 204));
        txtsociety.setEditable(true);
        txtsociety.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Christian Union", "YCS" }));

        lblreligion3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblreligion3.setText("Parent Id");

        txtpid.setBackground(new java.awt.Color(255, 255, 204));
        txtpid.setToolTipText("");
        txtpid.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        org.jdesktop.layout.GroupLayout pnlotherdetailsLayout = new org.jdesktop.layout.GroupLayout(pnlotherdetails);
        pnlotherdetails.setLayout(pnlotherdetailsLayout);
        pnlotherdetailsLayout.setHorizontalGroup(
            pnlotherdetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlotherdetailsLayout.createSequentialGroup()
                .addContainerGap()
                .add(pnlotherdetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pnlotherdetailsLayout.createSequentialGroup()
                        .add(lblbcert2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 158, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(pnlotherdetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, txtkcpe)
                            .add(txtcclass)
                            .add(txthouse)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, txtsport, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .add(pnlotherdetailsLayout.createSequentialGroup()
                        .add(pnlotherdetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, lblreligion3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, lblstream, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, lblclass, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(lblkcpe, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, lbldoa, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, lblcclass, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, lblreligion1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, lblreligion2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, lblsex2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, lbldob2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .add(18, 18, 18)
                        .add(pnlotherdetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(txtfamily)
                            .add(txtdoa, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(txtclass, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(txtstream, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(txtclub, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(txtsociety, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(txtpid)))))
        );
        pnlotherdetailsLayout.setVerticalGroup(
            pnlotherdetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlotherdetailsLayout.createSequentialGroup()
                .add(pnlotherdetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(lbldoa, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .add(txtdoa, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(6, 6, 6)
                .add(pnlotherdetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblstream, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(txtstream, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(6, 6, 6)
                .add(pnlotherdetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(lblclass, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(pnlotherdetailsLayout.createSequentialGroup()
                        .add(4, 4, 4)
                        .add(txtclass)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnlotherdetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(txtkcpe)
                    .add(lblkcpe, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnlotherdetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblcclass, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(txtcclass, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(pnlotherdetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(txthouse, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lblreligion1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnlotherdetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(lblbcert2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(pnlotherdetailsLayout.createSequentialGroup()
                        .add(5, 5, 5)
                        .add(txtsport)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnlotherdetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(lbldob2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(pnlotherdetailsLayout.createSequentialGroup()
                        .add(txtclub, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                        .add(7, 7, 7)))
                .add(pnlotherdetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(lblsex2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(pnlotherdetailsLayout.createSequentialGroup()
                        .add(txtsociety, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(3, 3, 3)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnlotherdetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblreligion2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(txtfamily, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnlotherdetailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblreligion3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(txtpid, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(4, 4, 4))
        );

        btnsearch.setFont(new java.awt.Font("FreeSerif", 1, 12)); // NOI18N
        btnsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_primaryschoolmanagement_client/1372438975_Search.png"))); // NOI18N
        btnsearch.setText("Search Admission");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        txtsearch.setBackground(new java.awt.Color(255, 255, 204));
        txtsearch.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        org.jdesktop.layout.GroupLayout pnlmainLayout = new org.jdesktop.layout.GroupLayout(pnlmain);
        pnlmain.setLayout(pnlmainLayout);
        pnlmainLayout.setHorizontalGroup(
            pnlmainLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, pnlmainLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(pnlprsnldetails, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(pnlmainLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(pnlmainLayout.createSequentialGroup()
                        .add(txtsearch, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 227, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(btnsearch))
                    .add(pnlotherdetails, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(126, 126, 126))
        );
        pnlmainLayout.setVerticalGroup(
            pnlmainLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlmainLayout.createSequentialGroup()
                .add(pnlmainLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(txtsearch, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btnsearch, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(pnlmainLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pnlprsnldetails, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(pnlotherdetails, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
        );

        btnnewrecord.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnnewrecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_primaryschoolmanagement_client/1372439035_save_edit.png"))); // NOI18N
        btnnewrecord.setText("Add New Record");
        btnnewrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewrecordActionPerformed(evt);
            }
        });

        btnsave.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_primaryschoolmanagement_client/1372440201_Save.png"))); // NOI18N
        btnsave.setText("Save Record");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btnedit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_primaryschoolmanagement_client/1372440261_filesaveas.png"))); // NOI18N
        btnedit.setText("Edit Record");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btndelete.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_primaryschoolmanagement_client/1372440315_trash-can-delete.png"))); // NOI18N
        btndelete.setText("Delete Record");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(21, 21, 21)
                .add(pnlmain, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 880, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(btnnewrecord, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(btnsave, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(btnedit, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(btndelete, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(0, 0, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(lbldetails, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 335, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(346, 346, 346))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(98, 98, 98)
                        .add(btnnewrecord)
                        .add(18, 18, 18)
                        .add(btnsave)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btnedit)
                        .add(18, 18, 18)
                        .add(btndelete))
                    .add(layout.createSequentialGroup()
                        .add(6, 6, 6)
                        .add(lbldetails, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 53, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(pnlmain, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  public String dbusername="root";
 public  String dbhostip;
 public  String dbpassword;
public   String database;  
    public void dblogincred(){
    
        String fileName = "C:\\Users\\Public\\Documents\\dblogin.txt";

        try {
            // Use this for reading the data.
            String[] login=new String[10];
            byte[] buffer = new byte[1000];

            FileInputStream inputStream = 
                new FileInputStream(fileName);

            int total = 0;
            int nRead = 0;
            while((nRead = inputStream.read(buffer)) != -1) {
               
             login[total]= (new String(buffer));
                total += nRead;
                
            }
            if(login[1]!=null){
            dbpassword=login[1].trim();
            }
             if(login[0]!=null){
            dbhostip=login[0].trim();
            }
               inputStream.close();
               if(dbhostip.isEmpty()==false){
               int l=dbhostip.indexOf("n");
               int e=dbhostip.indexOf("%");
               
        dbpassword=dbhostip.substring(l+1,e).trim();
        database=dbhostip.substring(e+1).trim();
        dbhostip=dbhostip.substring(0, l).trim();
         System.out.println(""+dbhostip);
         System.out.println(""+database);
         System.out.println(""+dbpassword);
               }
          
        }
        catch(FileNotFoundException ex) {
            System.out.println(
                "Unable to open file '" + 
                fileName + "'");
      
        }
        catch(IOException ex) {
            System.out.println(
                "Error reading file '" 
                + fileName + "'");					
            
        }
         
    }
    private void btnbrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbrowseActionPerformed
        // TODO add your handling code here:
             
    JFileChooser chooser = new JFileChooser();
    ExampleFileFilter filter = new ExampleFileFilter();
    filter.addExtension("jpg");
    filter.addExtension("gif");
    filter.setDescription("JPG & GIF Images");
     int returnVal = chooser.showOpenDialog(this);
    if (returnVal == 0)
    {
      this.path = chooser.getSelectedFile().getPath();
      ImageIcon spic = new ImageIcon("" + chooser.getSelectedFile().getPath());
      Image sp = spic.getImage();
      Image resizedImage = sp.getScaledInstance(this.lblppic.getWidth(), this.lblppic.getHeight(), 0);
      ImageIcon rim = new ImageIcon(resizedImage);
      this.lblppic.setIcon(rim);
    } else {
      ImageIcon spic = new ImageIcon();
      Image sp = spic.getImage();
      Image resizedImage = sp.getScaledInstance(this.lblppic.getWidth(), this.lblppic.getHeight(), 0);
      ImageIcon rim = new ImageIcon(resizedImage);
      this.lblppic.setIcon(rim);
    }
   
    }//GEN-LAST:event_btnbrowseActionPerformed

    private void btnnewrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewrecordActionPerformed
        // TODO add your handling code here:
    txtstdadm.setText("")  ;
    txtstdfname.setText("");
    txtbcn.setText("");
    txtdob.setDate(null);
    txtdoa.setDate(null);
    txtgender.setSelectedItem("");
    txtclass.setSelectedItem("");
    txtstream.setSelectedItem("");
    txtsociety.setSelectedItem("");
    txtclub.setSelectedItem("");
    txtreligion.setSelectedItem("");
    txtsport.setSelectedItem("");
    txtfamily.setText("");
    txthouse.setText("");
    txtcclass.setText("");
    txtkcpe.setText("");
    txtpid.setText("");
   
    ImageIcon spic = new ImageIcon("");
    Image sp = spic.getImage();
    Image resizedImage = sp.getScaledInstance(this.lblppic.getWidth(), this.lblppic.getHeight(), 0);
    ImageIcon rim = new ImageIcon(resizedImage);
    this.lblppic.setIcon(rim);         
   
   
   
   
   
   
  
    
    
    
    
    
    }//GEN-LAST:event_btnnewrecordActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        try {
            // TODO add your handling code here:
    String number=txtsearch.getText();
    int no=Integer.parseInt(number);
Class.forName("com.mysql.jdbc.Driver");
   
              String host = "jdbc:mysql://"+dbhostip+":3306/"+database;
          String user = dbusername;
          String password = dbpassword;
          Connection con = DriverManager.getConnection(host, user, password);

          Statement stmt = con.createStatement();

          ResultSet rs = stmt.executeQuery("Select *from STUDENT where studentnumber= " + no);

          if (rs.next()) {
            JOptionPane.showMessageDialog(null, "Record found!");
            txtstdadm.setText(""+ rs.getInt("studentnumber"))  ;
            txtstdfname.setText(""+rs.getString("studentname"));
    txtbcn.setText(""+rs.getInt("Bcertnumber"));
    txtdob.setDate(rs.getDate("DOA"));
    txtdoa.setDate(rs.getDate("dob"));
    txtgender.setSelectedItem(""+rs.getString("sex"));
    txtclass.setSelectedItem(""+rs.getInt("class"));
    txtstream.setSelectedItem(""+rs.getString("stream"));
    txtsociety.setSelectedItem(""+rs.getString("society"));
    txtclub.setSelectedItem(""+rs.getString("club"));
    txtreligion.setSelectedItem(""+rs.getString("religion"));
    txtsport.setSelectedItem(""+rs.getString("sport"));
    txtfamily.setText(""+rs.getString("family"));
    txthouse.setText(""+rs.getString("House"));
    txtcclass.setText(""+rs.getInt("cclass"));
    txtkcpe.setText(""+rs.getString("kcpe"));
    txtpid.setText(""+ rs.getInt("ParentsId"));
    if(rs.getString("spic")!=null){
         try{
            ImageIcon spic = new ImageIcon(rs.getString("spic"));
            Image sp = spic.getImage();
            Image resizedImage = sp.getScaledInstance(this.lblppic.getWidth(), this.lblppic.getHeight(), 0);
            ImageIcon rim = new ImageIcon(resizedImage);
            this.lblppic.setIcon(rim);
         }
         catch(Exception ex){
             ex.printStackTrace();
         }
    }
          }
          else
          {
            JOptionPane.showMessageDialog(null, "No matching record found");
          }
        } catch (SQLException ex) {
            Logger.getLogger(student.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "The above input student Admno does not show any record of a student please try again ");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(student.class.getName()).log(Level.SEVERE, null, ex);
        }
   
  



    }//GEN-LAST:event_btnsearchActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver");
   
      String host = "jdbc:mysql://"+dbhostip+":3306/"+database;
      String user = dbusername;
      String password = dbpassword;
      Connection con = DriverManager.getConnection(host, user, password);
       
   
      String sport = (String)this.txtsport.getSelectedItem();
      String gender = (String)this.txtgender.getSelectedItem();
      String cls=(String)this.txtclass.getSelectedItem();
      String stream=(String)this.txtstream.getSelectedItem();
      String religion=(String)this.txtreligion.getSelectedItem();
      String club=(String)this.txtclub.getSelectedItem();
      String society=(String)this.txtsociety.getSelectedItem();
      String pic=path;
     

      
      
   
      


      PreparedStatement stmt = con.prepareStatement("INSERT INTO STUDENT VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");

      stmt.setInt(1, Integer.parseInt(txtstdadm.getText()));
      stmt.setString(2, txtstdfname.getText());
      stmt.setString(3, gender);
      stmt.setString(4, stream);
      stmt.setString(5, txthouse.getText());
            java.util.Date doa=txtdoa.getDate();
             java.sql.Date sqldoa=new java.sql.Date(doa.getTime());
      stmt.setDate(6,sqldoa );
      stmt.setInt(7,  Integer.parseInt(cls));
      stmt.setInt(8,  Integer.parseInt(txtpid.getText()));
      stmt.setInt(9, Integer.parseInt(txtbcn.getText()));
      stmt.setString(10,pic);
      stmt.setString(11,sport);
      stmt.setString(12,txtkcpe.getText());
      stmt.setString(13,club);
      stmt.setString(14,society);
      stmt.setString(15,txtfamily.getText());
      stmt.setInt(16,Integer.parseInt(txtcclass.getText()));
      stmt.setString(17,religion);
       java.util.Date dob=txtdob.getDate();
             java.sql.Date sqldob=new java.sql.Date(dob.getTime());
      stmt.setDate(18,sqldob);
    
       stmt.executeUpdate();
      JOptionPane.showMessageDialog(rootPane, "Save operation successfull");
    }
    catch (Exception e)
    {
      e.printStackTrace();
         JOptionPane.showMessageDialog(rootPane, "Save operation failed please check that all the fields are input well");
 
      
    }
        
        
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        
       if(main.txtcredentials.getText().equals("Administrator")){
             try {
                 Class.forName("com.mysql.jdbc.Driver");
   
      String host = "jdbc:mysql://"+dbhostip+":3306/"+database;
      String user = dbusername;
      String password = dbpassword;
      Connection con = DriverManager.getConnection(host, user, password);
       
   
      String sport = (String)this.txtsport.getSelectedItem();
      String gender = (String)this.txtgender.getSelectedItem();
      String cls=(String)this.txtclass.getSelectedItem();
      String stream=(String)this.txtstream.getSelectedItem();
      String religion=(String)this.txtreligion.getSelectedItem();
      String club=(String)this.txtclub.getSelectedItem();
      String society=(String)this.txtsociety.getSelectedItem();
      String pic=path;
     

      
      
   
      


      PreparedStatement stmt = con.prepareStatement("UPDATE STUDENT SET studentnumber=?,studentname=?,sex=?,stream=?,House=?,DOA=?,Class=?,ParentsId=?,Bcertnumber=?,spic=?,sport=?,kcpe=?,club=?,society=?,family=?,cclass=?,religion=?,dob=? WHERE studentnumber=?");

      stmt.setInt(1, Integer.parseInt(txtstdadm.getText()));
      stmt.setString(2, txtstdfname.getText());
      stmt.setString(3, gender);
      stmt.setString(4, stream);
      stmt.setString(5, txthouse.getText());
            java.util.Date doa=txtdoa.getDate();
             java.sql.Date sqldoa=new java.sql.Date(doa.getTime());
      stmt.setDate(6,sqldoa );
      stmt.setInt(7,  Integer.parseInt(cls));
      stmt.setInt(8,  Integer.parseInt(txtpid.getText()));
      stmt.setInt(9, Integer.parseInt(txtbcn.getText()));
      stmt.setString(10,pic);
      stmt.setString(11,sport);
      stmt.setString(12,txtkcpe.getText());
      stmt.setString(13,club);
      stmt.setString(14,society);
      stmt.setString(15,txtfamily.getText());
      stmt.setInt(16,Integer.parseInt(txtcclass.getText()));
      stmt.setString(17,religion);
       java.util.Date dob=txtdob.getDate();
             java.sql.Date sqldob=new java.sql.Date(dob.getTime());
      stmt.setDate(18,sqldob);
    stmt.setString(19,txtsearch.getText());
       stmt.executeUpdate();
      JOptionPane.showMessageDialog(rootPane, "Edit operation successfull");
    }
    catch (Exception e)
    {
      e.printStackTrace();
         JOptionPane.showMessageDialog(rootPane, "Edit operation failed please check that all the fields are input well");
 
      
    }   
       }
       else{
           JOptionPane.showMessageDialog(rootPane,"Insufficient rights to perform this action");
       }
    }//GEN-LAST:event_btneditActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
           
       if(main.txtcredentials.getText().equals("Administrator")){
          int c =JOptionPane.showConfirmDialog(rootPane,"Are you sure you want to delete this record?","Delete",0);
          if(c==0){
        try {
            // TODO add your handling code here:
             String number=txtsearch.getText();
        int no=Integer.parseInt(number);
Class.forName("com.mysql.jdbc.Driver");
   
                  String host = "jdbc:mysql://"+dbhostip+":3306/"+database;
              String user = dbusername;
              String password = dbpassword;
              Connection con = DriverManager.getConnection(host, user, password);

              Statement stmt = con.createStatement();

             int r= stmt.executeUpdate("Delete from STUDENT where studentnumber= " + no);
             if(r==1){
               JOptionPane.showMessageDialog(rootPane,"Record deleted !");

             }
             else{
               JOptionPane.showMessageDialog(rootPane,"Delete operation failed");
  
             }
        } catch (SQLException ex) {
            Logger.getLogger(student.class.getName()).log(Level.SEVERE, null, ex);
        }     catch (ClassNotFoundException ex) {
                  Logger.getLogger(student.class.getName()).log(Level.SEVERE, null, ex);
              }
        }}
    else{
           JOptionPane.showMessageDialog(rootPane,"Insufficient rights to perform this action");
       }
                                          

    }//GEN-LAST:event_btndeleteActionPerformed

    private void txtclassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtclassActionPerformed
        // TODO add your handling code here:
        String cclass=(String) txtclass.getSelectedItem();
        txtcclass.setText(cclass);
    }//GEN-LAST:event_txtclassActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbrowse;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnnewrecord;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnsearch;
    private javax.swing.JLabel lbladm;
    private javax.swing.JLabel lblbcert;
    private javax.swing.JLabel lblbcert2;
    private javax.swing.JLabel lblcclass;
    private javax.swing.JLabel lblclass;
    private javax.swing.JLabel lbldetails;
    private javax.swing.JLabel lbldoa;
    private javax.swing.JLabel lbldob;
    private javax.swing.JLabel lbldob2;
    private javax.swing.JLabel lblfullname;
    private javax.swing.JLabel lblkcpe;
    private javax.swing.JLabel lblpic;
    private javax.swing.JLabel lblppic;
    private javax.swing.JLabel lblreligion;
    private javax.swing.JLabel lblreligion1;
    private javax.swing.JLabel lblreligion2;
    private javax.swing.JLabel lblreligion3;
    private javax.swing.JLabel lblsex;
    private javax.swing.JLabel lblsex2;
    private javax.swing.JLabel lblstream;
    private javax.swing.JPanel pnlmain;
    private javax.swing.JPanel pnlotherdetails;
    private javax.swing.JPanel pnlprsnldetails;
    private javax.swing.JTextField txtbcn;
    private javax.swing.JTextField txtcclass;
    private javax.swing.JComboBox txtclass;
    private javax.swing.JComboBox txtclub;
    private com.toedter.calendar.JDateChooser txtdoa;
    private com.toedter.calendar.JDateChooser txtdob;
    private javax.swing.JTextField txtfamily;
    private javax.swing.JComboBox txtgender;
    private javax.swing.JTextField txthouse;
    private javax.swing.JTextField txtkcpe;
    private javax.swing.JTextField txtpid;
    private javax.swing.JComboBox txtreligion;
    private javax.swing.JTextField txtsearch;
    private javax.swing.JComboBox txtsociety;
    private javax.swing.JComboBox txtsport;
    private javax.swing.JTextField txtstdadm;
    private javax.swing.JTextField txtstdfname;
    private javax.swing.JComboBox txtstream;
    // End of variables declaration//GEN-END:variables
}
